import React from 'react'
import ReactDOM from 'react-dom/client'
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import './index.css'
import App from './App'
import Discover from './pages/Discover'
import LotDetail from './pages/LotDetail'
import Admin from './pages/Admin'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
const router=createBrowserRouter([{path:'/',element:<App/>,children:[{index:true,element:<Discover/>},{path:'lot/:id',element:<LotDetail/>},{path:'admin',element:<Admin/>}]}]);const qc=new QueryClient();ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={qc}><RouterProvider router={router}/></QueryClientProvider></React.StrictMode>)